name: Build

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image name to create'
        required: true

concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  DOCKER_BUILD_OPT: ""
  DOCKER_BUILD_IMAGE_NAME: gladia/fastertransformer-triton-backend
  DOCKER_BUILD_IMAGE_TAG: ""
  TAG: ${{ inputs.tag }}

jobs:

  build:
    runs-on: [self-hosted, k0s, build]
    steps:
      - name: Assert Image and tag
        run: |
          if [ "$TAG" == "" ]; then
            echo "DOCKER_BUILD_IMAGE_TAG=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          else
            echo "DOCKER_BUILD_IMAGE_TAG=wd-$TAG" >> $GITHUB_ENV
          fi

      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Build & Push
        env:
          DOCKER_BUILDKIT: 1
        run: >-
          docker build --pull
          ${{env.DOCKER_BUILD_OPT}}
          -t ${DOCKER_GLADIA_FQDN}/${{env.DOCKER_BUILD_IMAGE_NAME}}:${{env.DOCKER_BUILD_IMAGE_TAG}}
          -f docker/Dockerfile . &&
          docker push ${DOCKER_GLADIA_FQDN}/${{env.DOCKER_BUILD_IMAGE_NAME}}:${{env.DOCKER_BUILD_IMAGE_TAG}}
